### PR TITLE
Update front end packages

### PR DESCRIPTION
**Pull request by rwblair**
Some of the packages were over a year out of date. Incidentally the update from antd 2.x to 3.x makes the default language English, so now tables with nothing in them say 'no data' instead of 暂无数据.

### CODE REVIEW

**Comment by adelavega** [comment]
Awesome. Looks like the frontend build is no longer compiling, though. Probably would be good to thoroughly test this, as I expect some downstream bugs from so much upgrading. I'll miss the Chinese... It was "quirky".

**Comment by rwblair** [comment]
Yeah once I removed my local node_modules because Travis failed my local deploy stopped installing. So strange, had the tests passing and the site working but once I rm'd node_modules and tried to reinstall everything broke bad.

**Comment by adelavega** [comment]
Yeah, not surprised, but good thing to do anyways!

**Comment by adelavega** [comment]
hey, hows this coming along? looks like tests are passing now

**Comment by adelavega** [comment]
Allright, looks good merging!

**Pull request merged**
