### PR TITLE
Refactor analysis bundles, and add new analysis endpoints

### PR DESCRIPTION
**Pull request by adelavega**
WIP will address #142 

Uses Marshmallow schemas to create new "views" of the analysis. 

Still need to add file end points (such as tarball bundle and tsv events)

### CODE REVIEW

**Comment by adelavega** [comment]
Need to update tests, also

**Comment by qmac** [comment]
Can we do something more verbose like `full_analysis` instead of `full`?

**Comment by adelavega** [comment]
Well it's nested under `analysis` so i think analysis is implied. Other more descriptive ideas?

**Comment by qmac** [comment]
description? parameters? config? My main concern is that the file name once its retrieved is just `full` by default.

**Comment by adelavega** [comment]
Hmm maybe `specification` but either way I don't think you should worry about it much because a) can't you save to a new file name e.g. `full_analysis` and b) soon the bundle will include the file so you don't need to fetch it. and I can call it `full_analysis` or `analysis_specification`

**Pull request merged**
