### PR TITLE
Ingest using BIDSVariableEventCollection and from other sources

### PR DESCRIPTION
**Pull request by adelavega**
Addresses #187 and ingestion from physio

### CODE REVIEW

**Comment by adelavega** [comment]
- [x] Fix tests
- [ ] Add tests with external features + test on real inputs (physio + events)
- [ ] Minor improvements to updater ingestion logic
- [ ] Fix updater tests

**Comment by adelavega** [comment]
Currently, new variables are not showing up in load_event_variables in task.py, not sure why

Will try manually debugging (rdb is not working)

**Comment by tyarkoni** [comment]
ohh yeah

**Comment by adelavega** [comment]
Status: DenseColumns need to be resampled before ingesting into database

**Comment by adelavega** [comment]
Status: To fully test ingesting forrest, need to fix issues related to video stimuli, such as hashing, and properly converting.

**Pull request merged**
